@startuml

package "  "  as es.urjc.mastermind {
}
package "  "  as es.urjc.mastermind.views {
}
package "  "  as es.urjc.mastermind.models {
}
package "  "  as es.urjc.utils {
}
package "  "  as java.io {
}
package "  "  as java.util {
}

[mastermind.jar]
mastermind.jar *---> es.urjc.mastermind
mastermind.jar *---> es.urjc.mastermind.models
mastermind.jar *---> es.urjc.mastermind.views
mastermind.jar *---> es.urjc.utils
mastermind.jar *---> java.io
mastermind.jar *---> java.util

@enduml