
@startuml

package mastermind.controllers {

    abstract class Controller {
        # Session session
        ~ Controller(Session session)
        + abstract control(): void
    }

    abstract class InGameController {
        ~ InGameController(Session session)
        # abstract inGameControl(): void
        + abstract isActive(): boolean
        + control(): void
    }

    class ProposalController {
        - final Menu menu
        + ProposalController(Session session)
        + control(): void
    }

    class StartController {
        + StartController(Session session)
        + control(): void
    }

    class ResumeController {
        + ResumeController(Session session)
        + control(): void
    }

    class ActionController {
        ~ ActionController(Session session)
        # inGameControl(): void
        + isActive(): boolean
        - readProposedCombination(): ProposedCombination
    }

    class UndoController {
        ~ UndoController(Session session)
        # inGameControl(): void
        + isActive(): boolean
    }

    class RedoController {
        ~ RedoController(Session session)
        # inGameControl(): void
        + isActive(): boolean
    }
}

package mastermind.models {
    class Session
}

package mastermind.views {
    class StartView
    class Menu
    class ProposalView
    class MessageView
    class SecretCombinationView
    class ProposedCombinationView
    class ResultView
    class ResumeView
    class ColorView
    class ErrorView
}

package mastermind.utils {
    interface Command
}

Controller <|--- StartController
Controller <|--- ProposalController
Controller <|--- ResumeController
Controller <|--- InGameController

InGameController <|--- ActionController
InGameController <|--- UndoController
InGameController <|--- RedoController

ProposalController *----> ActionController
ProposalController *----> UndoController
ProposalController *----> RedoController

StartController ....> StartView
ResumeController ....> ResumeView

ActionController ....> ProposalView
ActionController ....> ColorView
ActionController ....> ErrorView

InGameController ....> MessageView
InGameController ....> SecretCombinationView
InGameController ....> ProposedCombinationView
InGameController ....> ResultView

Controller *--> Session
ProposalController *--> Menu
Menu *--> Command
Command ....> ActionController
Command ....> UndoController
Command ....> RedoController





@enduml